Move argon2 to first, average, worst scoring.
WebKit/JetStream pull request #24
Opened 2024-12-23 15:23 UTC by kmiller68

Since the non-simd version of the test is relatively slow I reduced the iteration/worst counts to 15/2, repsectively.

Also, I moved all the benchmark files to the argon2 directory to help organize the wasm directory a bit.

2025-01-21 14:06 UTC, kmiller68 commented
CC @danleh @camillobruni @eqrion @jandem for thoughts

2025-01-21 15:51 UTC, danleh commented
Regarding the `README.md` (which wasn't changed by this PR, but since I looked at it): Could you add a short description where the source code is coming from? Or ideally change `build.sh` to checkout/download it from some URL, so we could more easily update it with whatever the upstream is?

2025-01-21 16:44 UTC, danleh commented
Mhm, I think there is something wrong with the non-SIMD variant of this benchmark. In particular, the flamegraph/profile shows tons of samples attributed to capturing stack traces, caused by growing the memory inside `_emscripten_resize_heap` and `emscripten_realloc_buffer`. See screenshot:
![image](https://github.com/user-attachments/assets/cf280234-7423-4b0f-a041-ccfd4152ea87)

If you modify `emscripten_realloc_buffer` in `argon2-bundle.js` to not just swallow the error/failure to grow memory
```
                function emscripten_realloc_buffer(size) {
                    try {
                        wasmMemory.grow(size - buffer.byteLength + 65535 >>> 16);
                        updateGlobalBufferAndViews(wasmMemory.buffer);
                        return 1
                    } catch (e) { console.log(e) }
                }
```
you get tons of errors, e.g., in d8 `RangeError: WebAssembly.Memory.grow(): Maximum memory size exceeded` or in jsc `RangeError: WebAssembly.Memory.grow expects the grown size to be a valid page count`.

I will briefly try to rebuild this from source to diagnose further. @kmiller68 have you seen this before or is this just a problem on my end? Do you have more information on why/how the memory usage of the non-SIMD variant could be higher than the SIMD variant?
For the time being, I don't think the non-SIMD variant is measuring something sensible.

2025-01-21 16:46 UTC, danleh requested changes

2025-01-21 16:46 UTC, danleh commented on JetStreamDriver.js
> +            "./wasm/argon2/argon2.js",
Similar to the other Emscripten-built line items, could we move the generated files in a `build/` subdirectory, to distinguish them from manually written code, such as `benchmark.js` (just so we/someone in the future doesn't end up mixing/interjecting manually written with generated code again).

2025-01-21 16:46 UTC, danleh commented on JetStreamDriver.js
> +            "./wasm/argon2/argon2.js",
Also, is it correct that both `benchmark.js` and `argon2.js` were written by you (or your colleagues)?

2025-01-21 16:46 UTC, danleh commented on JetStreamDriver.js
> +        iterations: 15,
Even with only 15 iterations, the non-SIMD variant runs quite long (>1 minute), while the SIMD variant runs ~2-3s with the same number of iterations. I am bit surprised by that stark difference (30x or more), so I will spend a brief time trying to understand why we are that slow. We do expect the SIMD and non-SIMD variant to do essentially the same amount of work, right?

2025-01-21 17:03 UTC, danleh commented
(lone comment, since the file wasn't changed in this PR): I believe the `../` prefix should be stripped from the destination paths in line 17 and 21 of `wasm/argon2/build.sh`, see https://github.com/WebKit/JetStream/blob/ab7d6d00b2eb6ce427aad4a4f3f5ebfb7e594924/wasm/argon2/build.sh#L17

2025-02-11 17:09 UTC, kmiller68 commented
Closing this in favor of https://github.com/WebKit/JetStream/pull/47

2025-02-11 17:09 UTC, closed without merging